(source melpa)
(source org)
(source gnu)

(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")
(depends-on "pretty-symbols")
(depends-on "async")
(depends-on "company")
(depends-on "exec-path-from-shell")
(depends-on "undo-tree")
(depends-on "simpleclip")
; (depends-on "restclient")
; (depends-on "shut-up")
(depends-on "solarized-theme")
(depends-on "auto-complete")
(depends-on "ghc")
(depends-on "ghci-completion")
(depends-on "company-ghc")
; (depends-on "flymake-haskell-multi")
; (depends-on "flymake-hlint")
(depends-on "flycheck")
(depends-on "haskell-mode")
; (depends-on "textmate")
(depends-on "shm")
; (depends-on "ergoemacs-mode")
(depends-on "flx-ido")
(depends-on "ido-vertical-mode")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-ag")
; ace-jump-mode
; ace-jump-buffer
(depends-on "scala-mode2")
(depends-on "ensime")
(depends-on "sbt-mode")
(depends-on "idris-mode")
(depends-on "rust-mode")
(depends-on "flycheck-rust")
