(source melpa)
(source org)

(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")
; (depends-on "restclient")
; (depends-on "shut-up")
(depends-on "solarized-theme")
(depends-on "auto-complete")
(depends-on "ghc")
(depends-on "ghci-completion")
(depends-on "flymake-haskell-multi")
(depends-on "flymake-hlint")
(depends-on "haskell-mode")
; (depends-on "textmate")
(depends-on "shm")
(depends-on "hi2")
; (depends-on "ergoemacs-mode")
; (depends-on "helm")
; (depends-on "smex")
; ace-jump-mode
; ace-jump-buffer
; lispy
