flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
# - HaRe-0.8.2.1
# - MonadRandom-0.4.1
# - StateVar-1.1.0.1
# - ansi-terminal-0.6.2.3
# - async-2.0.2
# - base-orphans-0.4.4
# - bifunctors-5.1
# - cabal-helper-0.6.2.0
# - cereal-0.4.1.1
# - cmdargs-0.10.13
# - comonad-4.2.7.2
# - contravariant-1.3.3
# - cpphs-1.19.3
# - distributive-0.4.4
# - djinn-ghc-0.0.2.3
# - djinn-lib-0.0.1.2
# - either-4.4.1
# - exceptions-0.8.0.2
# - extra-1.4.2
# - fclabels-2.0.2.3
# - free-4.12.1
# - ghc-mod-5.4.0.0
# - ghc-paths-0.1.0.9
# - ghc-syb-utils-0.2.3
# - ghci-ng-10.0.0
# - ghcid-0.5
# - hashable-1.2.3.3
# - haskell-src-exts-1.17.1
# - hasktags-0.69.1
# - hdevtools-0.1.2.1
# - hindent-4.6.0
# - hlint-1.9.25
# - hoogle-4.2.43
# - hscolour-1.23
# - hsdev-0.1.4.3
# - mmorph-1.0.4
# - monad-control-1.0.0.4
# - monad-journal-0.7.1
# - mtl-2.2.1
# - old-locale-1.0.0.7
# - old-time-1.1.0.3
# - pipes-4.1.7
# - polyparse-1.11
# - prelude-extras-0.4.0.2
# - profunctors-5.1.2
# - random-1.1
# - refact-0.3.0.2
# - semigroupoids-5.0.0.4
# - semigroups-0.18.0.1
# - split-0.2.2
# - stm-2.4.4
# - structured-haskell-mode-1.0.20
# - stylish-haskell-0.5.14.4
# - syb-0.6
# - tagged-0.8.2
# - temporary-1.2.0.3
- text-1.2.1.3
# - transformers-base-0.4.4
# - transformers-compat-0.4.0.4
# - uniplate-1.6.12
# - unordered-containers-0.2.5.1
# - utf8-string-1.0.1.1
# - void-0.7.1
resolver: nightly-2015-12-14
